semaphores: main_semaphores.cpp
	g++ -g main_semaphores.cpp -o main_semaphores -lpthread
	./main_semaphores

mutexes: main_mutexes.cpp
	g++ -g main_mutexes.cpp -o main_mutexes -lpthread
	./main_mutexes

semaphores_block: main_semaphores_blocking.cpp
	g++ -g main_semaphores_blocking.cpp -o main_semaphores_blocking -lpthread
	./main_semaphores_blocking

pi_number: main_pi_number.cpp
	g++ -g main_pi_number.cpp -o main_pi_number -lpthread
	./main_pi_number 4

pi_number_signal: main_pi_number_signal.cpp
	g++ -g main_pi_number_signal.cpp -o main_pi_number_signal -lpthread
	./main_pi_number_signal 4

